const DarkTheme = {
  dark: true,
  colors: {
    purple: {
      primary: '#9333ea',
      background: '#3A2A46',
      backgroundSecondary: '#4C4452',
      card: '#FFE9FF',
      textPrimary: '#FFF',
      white: '#fff',
      textSecondary: '#9ca3af',
      border: '#B2A8B8',
      notification: 'rgb(255, 69, 58)',
    },
    red: {
      primary: '#ef4444',
      background: '#57423F',
      backgroundSecondary: '#A4666C',
      card: '#FFE9FF',
      textPrimary: '#FFF',
      white: '#fff',
      textSecondary: '#F1DEDF',
      border: '#836561',
      notification: 'rgb(255, 69, 58)',
    },
    indigo: {
      primary: '#6366f1',
      background: '#484554',
      backgroundSecondary: '#938BB7',
      card: '#FFE9FF',
      textPrimary: '#FFF',
      white: '#fff',
      textSecondary: '#FAF8FF',
      border: '#B2A8B8',
      notification: 'rgb(255, 69, 58)',
    },
    teal: {
      primary: '#14b8a6',
      background: '#00362B',
      backgroundSecondary: '#344B47',
      card: '#FFE9FF',
      textPrimary: '#fff',
      white: '#fff',
      textSecondary: '#E0EBE5',
      border: '#007b62',
      notification: 'rgb(255, 69, 58)',
    },
  },
};
export default DarkTheme;
