const LightTheme = {
  dark: false,
  colors: {
    purple: {
      primary: '#9333ea',
      background: '#d9c6ea',
      backgroundSecondary: '#efecff',
      card: '#FFE9FF',
      textPrimary: '#000',
      white: '#fff',
      textSecondary: '#9ca3af',
      border: 'rgb(199, 199, 204)',
      notification: 'rgb(255, 69, 58)',
    },
    red: {
      primary: '#ef4444',
      background: '#EFA69D',
      backgroundSecondary: '#FFE5DD',
      card: '#FFE9FF',
      textPrimary: '#000',
      white: '#fff',
      textSecondary: '#798897',
      border: '#FFF6F4',
      notification: 'rgb(255, 69, 58)',
    },
    indigo: {
      primary: '#6366f1',
      background: '#AEA5DB',
      backgroundSecondary: '#d3d0e9',
      card: '#FFE9FF',
      textPrimary: '#000',
      white: '#fff',
      textSecondary: '#938BB7',
      border: 'rgb(199, 199, 204)',
      notification: 'rgb(255, 69, 58)',
    },
    teal: {
      primary: '#14b8a6',
      background: '#E0EBE5',
      backgroundSecondary: '#569D92',
      card: '#FFE9FF',
      textPrimary: '#000',
      white: '#fff',
      textSecondary: '#E0EBE5',
      border: 'rgb(199, 199, 204)',
      notification: 'rgb(255, 69, 58)',
    },
  },
};
export default LightTheme;
